# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lanzou-gui/lanzou.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.share_tab = QtWidgets.QWidget()
        self.share_tab.setObjectName("share_tab")
        self.horizontalLayout_7 = QtWidgets.QGridLayout(self.share_tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_share = QtWidgets.QVBoxLayout()
        self.verticalLayout_share.setObjectName("verticalLayout_share")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_share_url = QtWidgets.QLabel(self.share_tab)
        self.label_share_url.setObjectName("label_share_url")
        self.gridLayout.addWidget(self.label_share_url, 0, 0, 1, 1)
        self.line_share_url = QtWidgets.QLineEdit(self.share_tab)
        self.line_share_url.setObjectName("line_share_url")
        self.gridLayout.addWidget(self.line_share_url, 0, 1, 1, 1)
        self.btn_extract = QtWidgets.QPushButton(self.share_tab)
        self.btn_extract.setObjectName("btn_extract")
        self.gridLayout.addWidget(self.btn_extract, 0, 2, 1, 1)
        self.table_share = QtWidgets.QTableView(self.share_tab)
        self.table_share.setObjectName("table_share")
        self.gridLayout.addWidget(self.table_share, 1, 0, 1, 3)
        self.verticalLayout_share.addLayout(self.gridLayout)
        self.horizontalLayout_share = QtWidgets.QHBoxLayout()
        self.horizontalLayout_share.setObjectName("horizontalLayout_share")
        self.btn_share_select_all = QtWidgets.QPushButton(self.share_tab)
        self.btn_share_select_all.setObjectName("btn_share_select_all")
        self.horizontalLayout_share.addWidget(self.btn_share_select_all)
        self.label_dl_path = QtWidgets.QLabel(self.share_tab)
        self.label_dl_path.setObjectName("label_dl_path")
        self.horizontalLayout_share.addWidget(self.label_dl_path)
        self.btn_share_dl = QtWidgets.QPushButton(self.share_tab)
        self.btn_share_dl.setObjectName("btn_share_dl")
        self.horizontalLayout_share.addWidget(self.btn_share_dl)
        self.verticalLayout_share.addLayout(self.horizontalLayout_share)
        self.horizontalLayout_7.addLayout(self.verticalLayout_share, 0, 0, 1, 1)
        self.tabWidget.addTab(self.share_tab, "")
        self.disk_tab = QtWidgets.QWidget()
        self.disk_tab.setEnabled(True)
        self.disk_tab.setMinimumSize(QtCore.QSize(620, 0))
        self.disk_tab.setObjectName("disk_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.disk_tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_disk = QtWidgets.QVBoxLayout()
        self.horizontalLayout_disk.setObjectName("horizontalLayout_disk")
        self.horizontalLayout_disk_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_disk_1.setObjectName("horizontalLayout_disk_1")
        self.label_disk_location = QtWidgets.QLabel(self.disk_tab)
        self.label_disk_location.setObjectName("label_disk_location")
        self.horizontalLayout_disk_1.addWidget(self.label_disk_location)
        self.line_location = QtWidgets.QLineEdit(self.disk_tab)
        self.line_location.setObjectName("line_location")
        self.horizontalLayout_disk_1.addWidget(self.line_location)
        self.btn_location = QtWidgets.QPushButton(self.disk_tab)
        self.btn_location.setObjectName("btn_location")
        self.horizontalLayout_disk_1.addWidget(self.btn_location)
        self.horizontalLayout_disk.addLayout(self.horizontalLayout_disk_1)
        self.table_disk = QtWidgets.QTableView(self.disk_tab)
        self.table_disk.setObjectName("table_disk")
        self.horizontalLayout_disk.addWidget(self.table_disk)
        self.horizontalLayout_disk_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_disk_2.setObjectName("horizontalLayout_disk_2")
        self.btn_disk_select_all = QtWidgets.QPushButton(self.disk_tab)
        self.btn_disk_select_all.setObjectName("btn_disk_select_all")
        self.horizontalLayout_disk_2.addWidget(self.btn_disk_select_all)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_disk_2.addItem(spacerItem)
        self.btn_disk_delect = QtWidgets.QPushButton(self.disk_tab)
        self.btn_disk_delect.setObjectName("btn_disk_delect")
        self.horizontalLayout_disk_2.addWidget(self.btn_disk_delect)
        self.btn_disk_dl = QtWidgets.QPushButton(self.disk_tab)
        self.btn_disk_dl.setObjectName("btn_disk_dl")
        self.horizontalLayout_disk_2.addWidget(self.btn_disk_dl)
        self.horizontalLayout_disk.addLayout(self.horizontalLayout_disk_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_disk)
        self.tabWidget.addTab(self.disk_tab, "")
        self.upload_tab = QtWidgets.QWidget()
        self.upload_tab.setObjectName("upload_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.upload_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_up = QtWidgets.QGridLayout()
        self.gridLayout_up.setObjectName("gridLayout_up")
        self.label_up_select_file = QtWidgets.QLabel(self.upload_tab)
        self.label_up_select_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up_select_file.setObjectName("label_up_select_file")
        self.gridLayout_up.addWidget(self.label_up_select_file, 0, 1, 1, 1)
        self.line_up_files = QtWidgets.QLineEdit(self.upload_tab)
        self.line_up_files.setObjectName("line_up_files")
        self.gridLayout_up.addWidget(self.line_up_files, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_up.addItem(spacerItem1, 5, 1, 1, 1)
        self.label_up_cloud_path = QtWidgets.QLabel(self.upload_tab)
        self.label_up_cloud_path.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up_cloud_path.setObjectName("label_up_cloud_path")
        self.gridLayout_up.addWidget(self.label_up_cloud_path, 3, 1, 1, 1)
        self.btn_upload = QtWidgets.QPushButton(self.upload_tab)
        self.btn_upload.setObjectName("btn_upload")
        self.gridLayout_up.addWidget(self.btn_upload, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_up.addItem(spacerItem2, 2, 1, 1, 1)
        self.line_up_cloud_path = QtWidgets.QLineEdit(self.upload_tab)
        self.line_up_cloud_path.setObjectName("line_up_cloud_path")
        self.gridLayout_up.addWidget(self.line_up_cloud_path, 4, 0, 1, 3)
        self.horizontalLayout_4.addLayout(self.gridLayout_up)
        self.tabWidget.addTab(self.upload_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 30))
        self.menubar.setObjectName("menubar")
        self.acount = QtWidgets.QMenu(self.menubar)
        self.acount.setObjectName("acount")
        self.files = QtWidgets.QMenu(self.menubar)
        self.files.setObjectName("files")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.login = QtWidgets.QAction(MainWindow)
        self.login.setObjectName("login")
        self.logout = QtWidgets.QAction(MainWindow)
        self.logout.setObjectName("logout")
        self.upload = QtWidgets.QAction(MainWindow)
        self.upload.setObjectName("upload")
        self.download = QtWidgets.QAction(MainWindow)
        self.download.setObjectName("download")
        self.delect = QtWidgets.QAction(MainWindow)
        self.delect.setObjectName("delect")
        self.share = QtWidgets.QAction(MainWindow)
        self.share.setObjectName("share")
        self.how = QtWidgets.QAction(MainWindow)
        self.how.setObjectName("how")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.acount.addSeparator()
        self.acount.addAction(self.login)
        self.acount.addAction(self.logout)
        self.files.addAction(self.upload)
        self.files.addAction(self.download)
        self.files.addAction(self.delect)
        self.files.addAction(self.share)
        self.help.addAction(self.how)
        self.help.addAction(self.about)
        self.menubar.addAction(self.acount.menuAction())
        self.menubar.addAction(self.files.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_share_url.setText(_translate("MainWindow", "蓝奏链接"))
        self.btn_extract.setText(_translate("MainWindow", "提取"))
        self.btn_share_select_all.setText(_translate("MainWindow", "全选"))
        self.label_dl_path.setText(_translate("MainWindow", "文件下载路径"))
        self.btn_share_dl.setText(_translate("MainWindow", "下载选中文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.share_tab), _translate("MainWindow", "蓝奏云链接提取"))
        self.label_disk_location.setText(_translate("MainWindow", "位置"))
        self.btn_location.setText(_translate("MainWindow", "跳转"))
        self.btn_disk_select_all.setText(_translate("MainWindow", "全选"))
        self.btn_disk_delect.setText(_translate("MainWindow", "删除"))
        self.btn_disk_dl.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.disk_tab), _translate("MainWindow", "我的蓝奏云"))
        self.label_up_select_file.setText(_translate("MainWindow", "选择文件"))
        self.label_up_cloud_path.setText(_translate("MainWindow", "上传路径"))
        self.btn_upload.setText(_translate("MainWindow", "上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.upload_tab), _translate("MainWindow", "上传文件"))
        self.acount.setTitle(_translate("MainWindow", "登录"))
        self.files.setTitle(_translate("MainWindow", "文件"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.toolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.login.setText(_translate("MainWindow", "登录"))
        self.logout.setText(_translate("MainWindow", "登出"))
        self.upload.setText(_translate("MainWindow", "上传"))
        self.download.setText(_translate("MainWindow", "下载"))
        self.delect.setText(_translate("MainWindow", "删除"))
        self.share.setText(_translate("MainWindow", "分享"))
        self.how.setText(_translate("MainWindow", "使用说明"))
        self.about.setText(_translate("MainWindow", "关于"))
